### ISSUE TITLE
PyGrid integration in OpenHWControl

### ISSUE THREAD

**Issue by akej74** [kusti8/OpenHWControl#4]
Hi,

I just like to mention that there is a new project for controlling the Grid V2, [PyGrid](https://github.com/andyatgh/pygrid) by that may be interesting to include in OpenHWControl, as an alternative to Grid Control. PyGrid uses a JSON based UI which may be easier to integrate.

Anyway, just an idea :-)

**Comment by kusti8** [comment]
I'm not really maintaining this until I am able to get the devices for myself. If I can get a grid, I'll look into it. Thanks!
